name: shnuljoe
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.21

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #UI
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^9.2.0
  flutter_screenutil: ^5.0.0+2
  flutter_svg: ^1.0.3
  flutter_spinkit: ^4.1.2
  auto_size_text: ^3.0.0
  bubble: ^1.2.1
  flutter_switch: ^0.3.2
  screenshot: ^1.2.3
  image_picker: ^0.8.4
  persistent_bottom_nav_bar: ^4.0.2
  connectivity_plus: ^2.2.0
  audioplayers: ^0.20.1
  flutter_share_me:
    git:
      url: https://github.com/jordanjanaq/flutter_share_me
  #flutter_social_content_share:
 #   git:
   #   url: git://github.com/bhagyashreekhatri/flutter_social_content_share.git











  dots_indicator: ^2.0.0
  #StateManagement
  provider: ^6.0.2
  #firebase
  firebase_core: 1.3.0
  #Auth
  preload_page_view: ^0.1.6
  firebase_auth: ^1.4.0
  firebase_analytics: ^8.1.2
  #flutter_facebook_login: ^3.0.0
  shared_preferences: ^2.0.5
  #Storage
  cloud_firestore: ^2.2.1
  firebase_storage: ^8.1.2
  #Location
  firebase_core_platform_interface: ^4.0.1
  geolocator: ^8.0.3
  #geocoder: ^0.2.1
  geocoding: ^2.0.0
  #dateTime
  intl: ^0.17.0

  #API
  http: ^0.13.0
  location: ^4.3.0
  firebase_performance: ^0.7.0+5
  cached_network_image:
  #Function
  firebase_crashlytics: ^2.0.6
  firebase_messaging: ^10.0.3
  chewie: ^1.2.2
  video_player: ^2.2.3
  assets_audio_player: ^3.0.3+3
  highlighter_coachmark: ^0.0.3
  permission_handler: ^8.1.4+2
  url_launcher: ^6.0.9
  super_tooltip: ^1.0.1
  #audioplayers: ^0.20.0
  #audioplayer: ^0.8.1
  #just_audio: ^0.9.10
  #linked_scroll_controller: ^0.2.0
  simple_tooltip: ^1.0.0
  flutter_facebook_auth: ^3.5.7
  sign_in_with_apple: ^3.3.0
  the_apple_sign_in: ^1.1.1
  easy_localization: ^3.0.0
 
  #flutter_login_facebook: ^1.1.0
  #flutter_secure_storage: ^4.0.0
  #before_after: ^2.1.0

  #translator:
  translator: ^0.1.7
  google_fonts: ^2.2.0










dev_dependencies:
  flutter_test:
    sdk: flutter
    #IconLauncher
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - icons/
    - images/
    - images/weatherIcons/
    - assets/facebookIcon.png
    - assets/translations/


  fonts:
    - family: DG-Bebo
      fonts:
        - asset: fonts/DG-Bebo-B.ttf
    - family: BalooBhaijaan2
      fonts:
        - asset: fonts/BalooBhaijaan2-Bold.ttf
        - asset: fonts/BalooBhaijaan2-Regular.ttf
        - asset: fonts/BalooBhaijaan2-Medium.ttf
        - asset: fonts/BalooBhaijaan2-SemiBold.ttf
        - asset: fonts/BalooBhaijaan2-ExtraBold.ttf
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
